### ISSUE TITLE
ERROR: Repository has multiple remotes.

### ISSUE THREAD

**Issue by EricForgy** [GunnarFarneback/LocalRegistry.jl#17]
Hi 👋 

I'm giving this packaga a spin. It looks helpful 👍 

I am trying to register a package (without `push`) and got the error:

```
ERROR: Repository has multiple remotes.
```

It is true. My repository does have multiple remotes, but I need multiple remotes. Is there a workaround (other than removing a remote)? I'm not sure why remotes should even matter since I am doing everything locally for now.

**Comment by EricForgy** [comment]
I found it!

There is a keyword `repo` for `register` 👍 

We need the repo url to register a new package and that info is not necessarily in Project.toml, so it tries to obtain it from the remote. 

Btw, if there is more than one remote, what would be the harm in grabbing the URL from the first one (or any one). Or even grabbing it from all and comparing? Making it error seems a little harsh.

I'm kind of under some serious time constraints right now, but if nobody beats me to it, I can try to submit a PR to the docs to clarify this.

**Comment by GunnarFarneback** [comment]
> We need the repo url to register a new package and that info is not necessarily in Project.toml, so it tries to obtain it from the remote.

Yes, Pkg needs a repo URL so that `add` with branch or `dev` with package name can work. I guess it's possible to include a URL in `Project.toml` but it's not standard practice, so the `git remote` is the best place to find it unless it's explicitly given.

> Btw, if there is more than one remote, what would be the harm in grabbing the URL from the first one (or any one). Or even grabbing it from all and comparing? Making it error seems a little harsh.

Taking the first one and warning about there being more to choose from would be reasonable. Looking at all of them to see if they have the same URL seems over-ambitious, that should be an unusual setup.
